# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agl/vss-notification.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61gl/vss-notification.proto\x12\x03\x61gl\x1a\x1fgoogle/protobuf/timestamp.proto\"U\n\x18SignalUpdateNotification\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\'\n\x07signals\x18\x02 \x03(\x0b\x32\x16.agl.SignalUpdateEntry\"\xc6\x04\n\x11SignalUpdateEntry\x12\x0e\n\x04path\x18\x01 \x01(\tH\x00\x12\x0e\n\x04uuid\x18\x02 \x01(\tH\x00\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x06string\x18\x0b \x01(\tH\x01\x12\x0e\n\x04\x62ool\x18\x0c \x01(\x08H\x01\x12\x0f\n\x05int32\x18\r \x01(\x11H\x01\x12\x0f\n\x05int64\x18\x0e \x01(\x12H\x01\x12\x10\n\x06uint32\x18\x0f \x01(\rH\x01\x12\x10\n\x06uint64\x18\x10 \x01(\x04H\x01\x12\x0f\n\x05\x66loat\x18\x11 \x01(\x02H\x01\x12\x10\n\x06\x64ouble\x18\x12 \x01(\x01H\x01\x12(\n\x0cstring_array\x18\x15 \x01(\x0b\x32\x10.agl.StringArrayH\x01\x12$\n\nbool_array\x18\x16 \x01(\x0b\x32\x0e.agl.BoolArrayH\x01\x12&\n\x0bint32_array\x18\x17 \x01(\x0b\x32\x0f.agl.Int32ArrayH\x01\x12&\n\x0bint64_array\x18\x18 \x01(\x0b\x32\x0f.agl.Int64ArrayH\x01\x12(\n\x0cuint32_array\x18\x19 \x01(\x0b\x32\x10.agl.Uint32ArrayH\x01\x12(\n\x0cuint64_array\x18\x1a \x01(\x0b\x32\x10.agl.Uint64ArrayH\x01\x12&\n\x0b\x66loat_array\x18\x1b \x01(\x0b\x32\x0f.agl.FloatArrayH\x01\x12(\n\x0c\x64ouble_array\x18\x1c \x01(\x0b\x32\x10.agl.DoubleArrayH\x01\x42\x08\n\x06signalB\x07\n\x05value\"\x1d\n\x0bStringArray\x12\x0e\n\x06values\x18\x01 \x03(\t\"\x1b\n\tBoolArray\x12\x0e\n\x06values\x18\x01 \x03(\x08\"\x1c\n\nInt32Array\x12\x0e\n\x06values\x18\x01 \x03(\x11\"\x1c\n\nInt64Array\x12\x0e\n\x06values\x18\x01 \x03(\x12\"\x1d\n\x0bUint32Array\x12\x0e\n\x06values\x18\x01 \x03(\r\"\x1d\n\x0bUint64Array\x12\x0e\n\x06values\x18\x01 \x03(\x04\"\x1c\n\nFloatArray\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\x1d\n\x0b\x44oubleArray\x12\x0e\n\x06values\x18\x01 \x03(\x01\x62\x06proto3')



_SIGNALUPDATENOTIFICATION = DESCRIPTOR.message_types_by_name['SignalUpdateNotification']
_SIGNALUPDATEENTRY = DESCRIPTOR.message_types_by_name['SignalUpdateEntry']
_STRINGARRAY = DESCRIPTOR.message_types_by_name['StringArray']
_BOOLARRAY = DESCRIPTOR.message_types_by_name['BoolArray']
_INT32ARRAY = DESCRIPTOR.message_types_by_name['Int32Array']
_INT64ARRAY = DESCRIPTOR.message_types_by_name['Int64Array']
_UINT32ARRAY = DESCRIPTOR.message_types_by_name['Uint32Array']
_UINT64ARRAY = DESCRIPTOR.message_types_by_name['Uint64Array']
_FLOATARRAY = DESCRIPTOR.message_types_by_name['FloatArray']
_DOUBLEARRAY = DESCRIPTOR.message_types_by_name['DoubleArray']
SignalUpdateNotification = _reflection.GeneratedProtocolMessageType('SignalUpdateNotification', (_message.Message,), {
  'DESCRIPTOR' : _SIGNALUPDATENOTIFICATION,
  '__module__' : 'agl.vss_notification_pb2'
  # @@protoc_insertion_point(class_scope:agl.SignalUpdateNotification)
  })
_sym_db.RegisterMessage(SignalUpdateNotification)

SignalUpdateEntry = _reflection.GeneratedProtocolMessageType('SignalUpdateEntry', (_message.Message,), {
  'DESCRIPTOR' : _SIGNALUPDATEENTRY,
  '__module__' : 'agl.vss_notification_pb2'
  # @@protoc_insertion_point(class_scope:agl.SignalUpdateEntry)
  })
_sym_db.RegisterMessage(SignalUpdateEntry)

StringArray = _reflection.GeneratedProtocolMessageType('StringArray', (_message.Message,), {
  'DESCRIPTOR' : _STRINGARRAY,
  '__module__' : 'agl.vss_notification_pb2'
  # @@protoc_insertion_point(class_scope:agl.StringArray)
  })
_sym_db.RegisterMessage(StringArray)

BoolArray = _reflection.GeneratedProtocolMessageType('BoolArray', (_message.Message,), {
  'DESCRIPTOR' : _BOOLARRAY,
  '__module__' : 'agl.vss_notification_pb2'
  # @@protoc_insertion_point(class_scope:agl.BoolArray)
  })
_sym_db.RegisterMessage(BoolArray)

Int32Array = _reflection.GeneratedProtocolMessageType('Int32Array', (_message.Message,), {
  'DESCRIPTOR' : _INT32ARRAY,
  '__module__' : 'agl.vss_notification_pb2'
  # @@protoc_insertion_point(class_scope:agl.Int32Array)
  })
_sym_db.RegisterMessage(Int32Array)

Int64Array = _reflection.GeneratedProtocolMessageType('Int64Array', (_message.Message,), {
  'DESCRIPTOR' : _INT64ARRAY,
  '__module__' : 'agl.vss_notification_pb2'
  # @@protoc_insertion_point(class_scope:agl.Int64Array)
  })
_sym_db.RegisterMessage(Int64Array)

Uint32Array = _reflection.GeneratedProtocolMessageType('Uint32Array', (_message.Message,), {
  'DESCRIPTOR' : _UINT32ARRAY,
  '__module__' : 'agl.vss_notification_pb2'
  # @@protoc_insertion_point(class_scope:agl.Uint32Array)
  })
_sym_db.RegisterMessage(Uint32Array)

Uint64Array = _reflection.GeneratedProtocolMessageType('Uint64Array', (_message.Message,), {
  'DESCRIPTOR' : _UINT64ARRAY,
  '__module__' : 'agl.vss_notification_pb2'
  # @@protoc_insertion_point(class_scope:agl.Uint64Array)
  })
_sym_db.RegisterMessage(Uint64Array)

FloatArray = _reflection.GeneratedProtocolMessageType('FloatArray', (_message.Message,), {
  'DESCRIPTOR' : _FLOATARRAY,
  '__module__' : 'agl.vss_notification_pb2'
  # @@protoc_insertion_point(class_scope:agl.FloatArray)
  })
_sym_db.RegisterMessage(FloatArray)

DoubleArray = _reflection.GeneratedProtocolMessageType('DoubleArray', (_message.Message,), {
  'DESCRIPTOR' : _DOUBLEARRAY,
  '__module__' : 'agl.vss_notification_pb2'
  # @@protoc_insertion_point(class_scope:agl.DoubleArray)
  })
_sym_db.RegisterMessage(DoubleArray)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIGNALUPDATENOTIFICATION._serialized_start=68
  _SIGNALUPDATENOTIFICATION._serialized_end=153
  _SIGNALUPDATEENTRY._serialized_start=156
  _SIGNALUPDATEENTRY._serialized_end=738
  _STRINGARRAY._serialized_start=740
  _STRINGARRAY._serialized_end=769
  _BOOLARRAY._serialized_start=771
  _BOOLARRAY._serialized_end=798
  _INT32ARRAY._serialized_start=800
  _INT32ARRAY._serialized_end=828
  _INT64ARRAY._serialized_start=830
  _INT64ARRAY._serialized_end=858
  _UINT32ARRAY._serialized_start=860
  _UINT32ARRAY._serialized_end=889
  _UINT64ARRAY._serialized_start=891
  _UINT64ARRAY._serialized_end=920
  _FLOATARRAY._serialized_start=922
  _FLOATARRAY._serialized_end=950
  _DOUBLEARRAY._serialized_start=952
  _DOUBLEARRAY._serialized_end=981
# @@protoc_insertion_point(module_scope)
